"""Generate the source-owned PDF fixture used by Inko tests and examples."""

from __future__ import annotations

import argparse
from pathlib import Path

from reportlab.lib.colors import HexColor, white
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


PAGE_WIDTH, PAGE_HEIGHT = A4
NAVY = HexColor("#0D1B3E")
AMBER = HexColor("#E8A045")
INK = HexColor("#263247")
MUTED = HexColor("#667085")
PALE = HexColor("#F7F3EC")
LINE = HexColor("#D7DCE5")


def draw_footer(pdf: canvas.Canvas, page_number: int) -> None:
    pdf.setStrokeColor(LINE)
    pdf.line(48, 40, PAGE_WIDTH - 48, 40)
    pdf.setFillColor(MUTED)
    pdf.setFont("Helvetica", 8)
    pdf.drawString(48, 25, "INKO-SAMPLE-001 | Synthetic fixture | No customer data")
    pdf.drawRightString(PAGE_WIDTH - 48, 25, f"Page {page_number} of 12")


def draw_header(pdf: canvas.Canvas, eyebrow: str, title: str) -> None:
    pdf.setFillColor(AMBER)
    pdf.setFont("Helvetica-Bold", 9)
    pdf.drawString(48, PAGE_HEIGHT - 55, eyebrow.upper())
    pdf.setFillColor(NAVY)
    pdf.setFont("Helvetica-Bold", 24)
    pdf.drawString(48, PAGE_HEIGHT - 88, title)
    pdf.setStrokeColor(AMBER)
    pdf.setLineWidth(2)
    pdf.line(48, PAGE_HEIGHT - 103, 150, PAGE_HEIGHT - 103)


def wrapped_text(
    pdf: canvas.Canvas,
    text: str,
    x: float,
    y: float,
    width: float,
    *,
    font: str = "Helvetica",
    size: int = 10,
    leading: int = 15,
    color=INK,
) -> float:
    words = text.split()
    lines: list[str] = []
    current = ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if pdf.stringWidth(candidate, font, size) <= width:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)

    pdf.setFillColor(color)
    pdf.setFont(font, size)
    for line in lines:
        pdf.drawString(x, y, line)
        y -= leading
    return y


def draw_cover(pdf: canvas.Canvas) -> None:
    pdf.setFillColor(NAVY)
    pdf.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, fill=1, stroke=0)
    pdf.setFillColor(AMBER)
    pdf.circle(PAGE_WIDTH - 105, PAGE_HEIGHT - 105, 44, fill=1, stroke=0)
    pdf.setStrokeColor(white)
    pdf.setLineWidth(0.8)
    for radius in (58, 72, 86):
        pdf.circle(PAGE_WIDTH - 105, PAGE_HEIGHT - 105, radius, fill=0, stroke=1)

    pdf.setFillColor(AMBER)
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(52, PAGE_HEIGHT - 160, "NEXT H | OPEN SOURCE ENGINEERING")
    pdf.setFillColor(white)
    pdf.setFont("Helvetica-Bold", 34)
    pdf.drawString(52, PAGE_HEIGHT - 215, "Inko PDF SDK")
    pdf.setFont("Helvetica", 21)
    pdf.drawString(52, PAGE_HEIGHT - 250, "Synthetic Integration Fixture")

    pdf.setFillColor(AMBER)
    pdf.rect(52, PAGE_HEIGHT - 310, 110, 4, fill=1, stroke=0)
    y = PAGE_HEIGHT - 350
    y = wrapped_text(
        pdf,
        "This document is generated by NextH for rendering, annotation, save, restore, and page-navigation tests.",
        52,
        y,
        420,
        size=12,
        leading=19,
        color=white,
    )
    y -= 10
    wrapped_text(
        pdf,
        "It contains no customer data, third-party prose, third-party images, or external font files.",
        52,
        y,
        420,
        size=12,
        leading=19,
        color=white,
    )

    pdf.setFillColor(HexColor("#B8C2D6"))
    pdf.setFont("Helvetica", 9)
    pdf.drawString(52, 86, "Document ID: INKO-SAMPLE-001")
    pdf.drawString(52, 70, "Fixture version: 1.0 | Authored and generated by NextH")


def draw_summary(pdf: canvas.Canvas) -> None:
    draw_header(pdf, "Fixture overview", "What this PDF exercises")
    items = [
        ("12 pages", "Supports page navigation, lazy rendering, and revisit checks."),
        ("Vector text", "Uses only PDF standard Helvetica fonts and source-owned copy."),
        ("Tables and rules", "Provides clear targets for pens, highlighters, shapes, and erasers."),
        ("Stable metadata", "Uses deterministic generation settings for repeatable review."),
    ]
    y = PAGE_HEIGHT - 150
    for index, (label, detail) in enumerate(items, start=1):
        pdf.setFillColor(PALE)
        pdf.roundRect(48, y - 64, PAGE_WIDTH - 96, 56, 8, fill=1, stroke=0)
        pdf.setFillColor(AMBER)
        pdf.circle(72, y - 36, 13, fill=1, stroke=0)
        pdf.setFillColor(NAVY)
        pdf.setFont("Helvetica-Bold", 10)
        pdf.drawCentredString(72, y - 40, str(index))
        pdf.setFont("Helvetica-Bold", 12)
        pdf.drawString(98, y - 29, label)
        pdf.setFillColor(MUTED)
        pdf.setFont("Helvetica", 9)
        pdf.drawString(98, y - 47, detail)
        y -= 78
    draw_footer(pdf, 2)


def draw_table_page(pdf: canvas.Canvas, page_number: int) -> None:
    draw_header(pdf, "Structured content", "Review matrix")
    headers = ["Item", "Owner", "State", "Review note"]
    widths = [150, 92, 80, 177]
    x0 = 48
    y0 = PAGE_HEIGHT - 145
    row_height = 34
    pdf.setFillColor(NAVY)
    pdf.rect(x0, y0, sum(widths), row_height, fill=1, stroke=0)
    x = x0
    pdf.setFillColor(white)
    pdf.setFont("Helvetica-Bold", 9)
    for header, width in zip(headers, widths):
        pdf.drawString(x + 8, y0 + 12, header)
        x += width

    states = ["Draft", "Review", "Approved", "Follow-up"]
    for row in range(10):
        y = y0 - (row + 1) * row_height
        pdf.setFillColor(PALE if row % 2 == 0 else white)
        pdf.rect(x0, y, sum(widths), row_height, fill=1, stroke=0)
        values = [
            f"Section {row + 1:02d}",
            f"Reviewer {(row % 3) + 1}",
            states[row % len(states)],
            "Synthetic row for annotation testing",
        ]
        x = x0
        pdf.setFillColor(INK)
        pdf.setFont("Helvetica", 8.5)
        for value, width in zip(values, widths):
            pdf.drawString(x + 8, y + 12, value)
            x += width

    pdf.setStrokeColor(LINE)
    x = x0
    for width in widths:
        pdf.line(x, y0 - 10 * row_height, x, y0 + row_height)
        x += width
    pdf.line(x, y0 - 10 * row_height, x, y0 + row_height)
    draw_footer(pdf, page_number)


def draw_annotation_page(pdf: canvas.Canvas, page_number: int, variant: int) -> None:
    titles = [
        "Annotation practice zones",
        "Save and restore checkpoints",
        "Layer comparison worksheet",
        "Long-document navigation",
        "Review decision record",
        "Host integration checklist",
        "Rendering contrast samples",
        "Keyboard and pointer notes",
    ]
    draw_header(pdf, f"Exercise {variant + 1:02d}", titles[variant])

    y = PAGE_HEIGHT - 145
    intro = (
        "Use this page as a neutral target for drawing, highlighting, selecting, clearing, "
        "saving, reloading, and comparing annotation state. All labels are synthetic."
    )
    y = wrapped_text(pdf, intro, 48, y, PAGE_WIDTH - 96, size=10, leading=15)
    y -= 18

    for block in range(3):
        block_y = y - block * 145
        pdf.setFillColor(PALE)
        pdf.roundRect(48, block_y - 112, PAGE_WIDTH - 96, 112, 8, fill=1, stroke=0)
        pdf.setFillColor(AMBER)
        pdf.setFont("Helvetica-Bold", 10)
        pdf.drawString(64, block_y - 25, f"ZONE {block + 1}")
        pdf.setFillColor(NAVY)
        pdf.setFont("Helvetica-Bold", 12)
        pdf.drawString(64, block_y - 46, f"Synthetic review prompt {variant + 1}.{block + 1}")
        wrapped_text(
            pdf,
            "Add a mark here, export canvasData, reload the document, and confirm that the host-provided state is restored as expected.",
            64,
            block_y - 65,
            PAGE_WIDTH - 160,
            size=8.5,
            leading=13,
            color=MUTED,
        )
        pdf.setStrokeColor(LINE)
        pdf.setDash(3, 3)
        pdf.line(64, block_y - 96, PAGE_WIDTH - 64, block_y - 96)
        pdf.setDash()

    draw_footer(pdf, page_number)


def draw_final_page(pdf: canvas.Canvas) -> None:
    draw_header(pdf, "Fixture provenance", "Rights-safe sample checklist")
    checks = [
        "Generated from scripts/generate-oss-sample-pdf.py",
        "No customer, government, or partner document content",
        "No personal information or external images",
        "No bundled font files; standard PDF Helvetica only",
        "Stable title, author, subject, and fixture identifier",
        "Suitable for source, build, example, and automated test paths",
    ]
    y = PAGE_HEIGHT - 150
    for item in checks:
        pdf.setFillColor(AMBER)
        pdf.circle(59, y + 3, 5, fill=1, stroke=0)
        pdf.setFillColor(INK)
        pdf.setFont("Helvetica", 11)
        pdf.drawString(76, y, item)
        y -= 42

    pdf.setFillColor(NAVY)
    pdf.roundRect(48, 120, PAGE_WIDTH - 96, 90, 10, fill=1, stroke=0)
    pdf.setFillColor(white)
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(68, 176, "End of synthetic fixture")
    wrapped_text(
        pdf,
        "If this file changes, regenerate it from source and repeat render, text, metadata, and viewer regression checks.",
        68,
        153,
        PAGE_WIDTH - 136,
        size=9.5,
        leading=15,
        color=white,
    )
    draw_footer(pdf, 12)


def generate(output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    pdf = canvas.Canvas(
        str(output),
        pagesize=A4,
        pageCompression=1,
        invariant=1,
    )
    pdf.setTitle("Inko PDF SDK Synthetic Integration Fixture")
    pdf.setAuthor("NextH")
    pdf.setSubject("Source-owned PDF fixture for Inko rendering and annotation tests")
    pdf.setKeywords("Inko, NextH, synthetic fixture, PDF SDK, open source")
    pdf.setCreator("NextH Inko OSS fixture generator")

    # Outline (bookmark) entries are part of the fixture on purpose: the viewer
    # extracts them through pdf.js getOutline(), so the fixture must exercise both
    # top-level entries and a nested level to cover the tree UI.
    draw_cover(pdf)
    pdf.bookmarkPage("sec-cover")
    pdf.addOutlineEntry("Cover", "sec-cover", level=0)
    pdf.showPage()

    draw_summary(pdf)
    pdf.bookmarkPage("sec-summary")
    pdf.addOutlineEntry("Executive summary", "sec-summary", level=0)
    pdf.showPage()

    draw_table_page(pdf, 3)
    pdf.bookmarkPage("sec-specification")
    pdf.addOutlineEntry("Specification table", "sec-specification", level=0)
    pdf.showPage()

    for page_number in range(4, 12):
        draw_annotation_page(pdf, page_number, page_number - 4)
        if page_number == 4:
            pdf.bookmarkPage("sec-annotations")
            pdf.addOutlineEntry("Annotation samples", "sec-annotations", level=0)
        pdf.bookmarkPage(f"sec-annotation-{page_number}")
        pdf.addOutlineEntry(
            f"Sample {page_number - 3}", f"sec-annotation-{page_number}", level=1
        )
        pdf.showPage()

    draw_final_page(pdf)
    pdf.bookmarkPage("sec-checklist")
    pdf.addOutlineEntry("Integration checklist", "sec-checklist", level=0)
    pdf.save()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("public/samples/inko-demo.pdf"),
        help="PDF output path relative to the current working directory",
    )
    args = parser.parse_args()
    generate(args.output.resolve())
    print(args.output.resolve())


if __name__ == "__main__":
    main()
